apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: disk-management-agent
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: disk-management-agent
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: disk-management-agent
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: disk-management-agent
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --health-probe-bind-address=:8081
        image: controller:latest
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: STORCLI_PATH
            value: "/host/libexec/MegaRAID/storcli/storcli64"
          - name: PERCCLI_PATH
            value: "/host/libexec/MegaRAID/perccli/perccli64"
          - name: SSACLI_PATH
            value: "/host/libexec/ssacli"
        ports: []
        securityContext:
          privileged: true
          runAsUser: 0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: megaraid
          mountPath: /host/libexec/MegaRAID
          readOnly: true
        - name: ssacli
          mountPath: /host/libexec/ssacli
          readOnly: true
        - name: dev
          mountPath: /dev
      volumes:
      - name: megaraid
        hostPath:
          path: /opt/MegaRAID/
          type: DirectoryOrCreate
      - name: ssacli
        hostPath:
          path: /usr/bin/ssacli
          type: FileOrCreate
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
