//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerRef) DeepCopyInto(out *ControllerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRef.
func (in *ControllerRef) DeepCopy() *ControllerRef {
	if in == nil {
		return nil
	}
	out := new(ControllerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredPhysicalDisk) DeepCopyInto(out *DiscoveredPhysicalDisk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredPhysicalDisk.
func (in *DiscoveredPhysicalDisk) DeepCopy() *DiscoveredPhysicalDisk {
	if in == nil {
		return nil
	}
	out := new(DiscoveredPhysicalDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveredPhysicalDisk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredPhysicalDiskList) DeepCopyInto(out *DiscoveredPhysicalDiskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiscoveredPhysicalDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredPhysicalDiskList.
func (in *DiscoveredPhysicalDiskList) DeepCopy() *DiscoveredPhysicalDiskList {
	if in == nil {
		return nil
	}
	out := new(DiscoveredPhysicalDiskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveredPhysicalDiskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredPhysicalDiskSpec) DeepCopyInto(out *DiscoveredPhysicalDiskSpec) {
	*out = *in
	out.Controller = in.Controller
	out.Slot = in.Slot
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredPhysicalDiskSpec.
func (in *DiscoveredPhysicalDiskSpec) DeepCopy() *DiscoveredPhysicalDiskSpec {
	if in == nil {
		return nil
	}
	out := new(DiscoveredPhysicalDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredPhysicalDiskStatus) DeepCopyInto(out *DiscoveredPhysicalDiskStatus) {
	*out = *in
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = new(bool)
		**out = **in
	}
	if in.Vendor != nil {
		in, out := &in.Vendor, &out.Vendor
		*out = new(string)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Serial != nil {
		in, out := &in.Serial, &out.Serial
		*out = new(string)
		**out = **in
	}
	if in.WWN != nil {
		in, out := &in.WWN, &out.WWN
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.JBOD != nil {
		in, out := &in.JBOD, &out.JBOD
		*out = new(bool)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.DevicePath != nil {
		in, out := &in.DevicePath, &out.DevicePath
		*out = new(string)
		**out = **in
	}
	if in.PermanentPath != nil {
		in, out := &in.PermanentPath, &out.PermanentPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredPhysicalDiskStatus.
func (in *DiscoveredPhysicalDiskStatus) DeepCopy() *DiscoveredPhysicalDiskStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveredPhysicalDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlotLocation) DeepCopyInto(out *SlotLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotLocation.
func (in *SlotLocation) DeepCopy() *SlotLocation {
	if in == nil {
		return nil
	}
	out := new(SlotLocation)
	in.DeepCopyInto(out)
	return out
}
